BidOneCodingTest/Models/ErrorViewModel.cs
using System;

namespace BidOneCodingTest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BidOneCodingTest/Models/UserConfiguration.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BidOneCodingTest.Models
{
    public class UserConfiguration
    {
        [Required]
        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [Required]
        [DisplayName("Last Name")]
        public string LastName { get; set; }
    }
}

BidOneCodingTest/Controllers/HomeController.cs
using System.Diagnostics;
using BidOneCodingTest.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace BidOneCodingTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BidOneCodingTest/Controllers/UserConfigurationController.cs
using System.Threading.Tasks;
using BidOneCodingTest.Models;
using Microsoft.AspNetCore.Mvc;

namespace BidOneCodingTest.Controllers
{
    public class UserConfigurationController : Controller
    {
        private readonly IUserConfigurationStorage _UserConfigurationStorage;

        public UserConfigurationController(IUserConfigurationStorage userConfigurationStorage)
        {
            _UserConfigurationStorage = userConfigurationStorage;
        }

        public async Task<ActionResult> Index()
        {
            var model = await _UserConfigurationStorage.GetUserConfigAsync();                        
            return View(model);
        }
                  
        public async Task<ActionResult> Edit()
        {
            var model = await _UserConfigurationStorage.GetUserConfigAsync();
            return View(model);
        }
                
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(UserConfiguration userConfig)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
               await _UserConfigurationStorage.SetUserConfigAsync(userConfig);
               return RedirectToAction(nameof(Index));    
            }           
        }
      

 
    }
}

BidOneCodingTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <h1 class="display-4">Welcome To BidOne </h1>      
    </div>

BidOneCodingTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BidOne Coding Test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BidOne Coding Test</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="UserConfiguration" asp-action="Index">User Configuration</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BidOne Coding Test
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BidOneCodingTest/Views/UserConfiguration/Edit.cshtml
@model BidOneCodingTest.Models.UserConfiguration
@{
    ViewData["Title"] = "Edit User Configuration";
}
<h1>Edit User Configuration</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="UserConfiguration" asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BidOneCodingTest/Views/UserConfiguration/Index.cshtml
@model BidOneCodingTest.Models.UserConfiguration

@{
    ViewData["Title"] = "User Configuration";
}
<h1>User Configuration</h1>
<h4>The system is currently configured for the following user:</h4>
<br />
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.LastName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit")
                </td>
            </tr>
        </tbody>
    </table>